version: '3'

services:
  slotegrator:
    build:
      context: ./app
      dockerfile: Dockerfile
    networks:
      - app-network
  
  nginx-ingress:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - slotegrator

networks:
  app-network:
    driver: bridge
